name: Check Syntax

on:
  push:
    branches:
      - main

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check syntax
        run: |
          bash -n preinstall.sh
          if [ $? -ne 0 ]; then
            echo "Syntax error"
            exit 1
          fi
